const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Adidas Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 3,
      brand: 'Adidas',
      rating: 4,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Jordan Slim Shirt',
      category: 'pants',
      image: '/images/p1.jpg',
      price: 564,
      countInStock: 7,
      brand: 'Jordan',
      rating: 5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'under Slim Shirt',
      category: 'pants',
      image: '/images/p1.jpg',
      price: 324,
      countInStock: 8,
      brand: 'under',
      rating: 3,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Rebok Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 8,
      brand: 'Rebook',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Lacoste Slim Shirt',
      category: 'pants',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
}

export default data
